function valuap(respuest){ 
	var reto;
	if(parseInt(respuest)==this.correcta){
		// var reto;
		alert("Es correcta");
		reto=true;
		return reto;
	}else{
		alert("Es false");
		return reto;
	}
}

function pregunta(pregun,respuesta1,respuesta2,respuesta3,respuesta4,correcta){
	this.pregun=pregun;
	this.respuestas=[];
	this.respuestas[0]=respuesta1;
	this.respuestas[1]=respuesta2;
	this.respuestas[2]=respuesta3;
	this.respuestas[3]=respuesta4;
	this.correcta=parseInt(correcta);
	this.ocupado=false;
	this.valuap=valuap;
}

var retorno=[];
var preguntas=[];


preguntas[0]=new pregunta("¿Qué es un grupo?","Un conjunto con una operación binaria y elementos neutros.","Un conjunto con una operación unaria y elementos neutros.","Un conjunto con una operación ternaria y elementos neutros","Un conjunto con una operación binaria y elementos inversos.",0);
preguntas[1]=new pregunta("¿Cuál es la propiedad que define a un grupo?","Asociatividad","Conmutatividad","Distributividad","Inversión",0);
preguntas[2]=new pregunta("¿Cuál es la propiedad que define a un semigrupo?","Asociatividad","Conmutatividad","Distributividad","Inversión",0);
preguntas[3]=new pregunta("¿Cuál es la diferencia entre un grupo y un semigrupo?","Un grupo tiene elementos inversos y un semigrupo no","Un semigrupo tiene elementos inversos y un grupo no","Un grupo es conmutativo y un semigrupo no","Un semigrupo es conmutativo y un grupo no",0);
preguntas[4]=new pregunta("¿Qué es un monoide?","Un semigrupo con un elemento neutro","Un grupo con un elemento neutro","Un semigrupo con elementos inversos","Un grupo con elementos inversos",0);
preguntas[5]=new pregunta("¿Cuál es la propiedad que define a un monoide?","Asociatividad","Conmutatividad","Distributividad","Inversión",0);
preguntas[6]=new pregunta("¿Cuál es la relación entre grupos y semigrupos?","Un grupo es un semigrupo con elementos inversos","Un semigrupo es un grupo con elementos inversos","No hay relación entre grupos y semigrupos","Los grupos y semigrupos son lo mismo",1);
preguntas[7]=new pregunta("¿Cuál es la relación entre grupos y monoides?","Un grupo es un monoide con elementos inversos","Un monoide es un grupo con elementos inversos","No hay relación entre grupos y monoides","Los grupos y monoides son lo mismo",1);
preguntas[8]=new pregunta("¿Qué es un homomorfismo?","Una función que preserva la estructura de grupo","Una función que intercambia elementos del grupo","Una función que agrega elementos al grupo","Una función que elimina elementos del grupo",0);
preguntas[9]=new pregunta("¿Qué es un isomorfismo?","Un homomorfismo biyectivo","Un homomorfismo inyectivo","Un homomorfismo sobreyectivo","Un homomorfismo que no es biyectivo",0);
preguntas[10]=new pregunta("¿Cuál es la definición de subgrupo?","Un subconjunto que es un grupo en sí mismo","Un subconjunto que es un semigrupo en sí mismo","Un subconjunto que es un monoide en sí mismo","Un subconjunto que es un homomorfismo en sí mismo",0);
preguntas[11]=new pregunta("¿Qué es un grupo abeliano?","Un grupo conmutativo","Un grupo no conmutativo","Un grupo con elementos inversos","Un grupo sin elementos inversos",0);
preguntas[12]=new pregunta("¿Qué es un grupo simple?","Un grupo que no tiene subgrupos propios","Un grupo que tiene subgrupos propios","Un grupo abeliano","Un grupo conmutativo",0);
preguntas[13]=new pregunta("¿Cuál es la definición de un semigrupo matemático?","Un conjunto no vacío G con una operación binaria * que satisface la cerradura y la asociatividad.", "Un conjunto vacío G con una operación binaria * que satisface la cerradura y la asociatividad.", "Un conjunto no vacío G con una operación binaria + que satisface la cerradura y la asociatividad.", "Un conjunto no vacío G con una operación binaria * que satisface la cerradura, la asociatividad y la existencia del elemento neutro.", 1);
preguntas[14]=new pregunta("¿Cuál es la definición de un monoide matemático?","Un conjunto no vacío G con una operación binaria * que satisface la cerradura, la asociatividad y la existencia del elemento neutro.", "Un conjunto no vacío G con una operación binaria * que satisface la cerradura, la asociatividad y la existencia del elemento inverso.", "Un conjunto vacío G con una operación binaria * que satisface la cerradura, la asociatividad y la existencia del elemento neutro.", "Un conjunto no vacío G con una operación binaria + que satisface la cerradura, la asociatividad y la existencia del elemento neutro.", 1);
preguntas[15]=new pregunta("¿Cuál es la propiedad asociativa en matemáticas?", "La propiedad de que el resultado de una operación binaria no depende del orden en que se realizan las operaciones.", "La propiedad de que el resultado de una operación binaria es el mismo independientemente de los operandos.", "La propiedad de que el resultado de una operación binaria es el mismo que el operando neutro.", "La propiedad de que el resultado de una operación binaria es el mismo que el inverso aditivo del operando.", 1);
preguntas[16]=new pregunta("¿Qué es el elemento neutro en un grupo matemático?", "Un elemento en el conjunto que, cuando se opera con cualquier otro elemento del conjunto, no cambia el valor de ese elemento.", "Un elemento en el conjunto que es igual a su propio inverso aditivo.", "Un elemento en el conjunto que siempre produce un valor de 0 cuando se opera con cualquier otro elemento del conjunto.", "Un elemento en el conjunto que siempre produce un valor de 1 cuando se opera con cualquier otro elemento del conjunto.", 1);
preguntas[17]=new pregunta("¿Qué es el inverso multiplicativo de un elemento en un grupo matemático?", "El elemento en el conjunto que, cuando se opera con el elemento original, produce el elemento neutro.", "El elemento en el conjunto que es igual a su propio inverso aditivo.", "El elemento en el conjunto que siempre produce un valor de 0 cuando se opera con cualquier otro elemento del conjunto.", "El elemento en el conjunto que siempre produce un valor de 1 cuando se opera con cualquier otro elemento del conjunto.", 1);
preguntas[18]=new pregunta("¿Qué es el orden de un elemento en un grupo matemático?", "El número más pequeño n tal que a^n = e, donde a es el elemento y e es el elemento neutro.", "El número más grande n tal que a^n = e, donde a es el elemento y e es el elemento neutro.", "El número más pequeño n tal que a^n = a, donde a es el elemento y e es el elemento neutro.", "El número más grande n tal que a^n = a, donde a es el elemento y e es el elemento neutro.", 1);
preguntas[19]=new pregunta("¿Qué es un subgrupo en un grupo matemático?", "Un subconjunto no vacío de un grupo que es cerrado bajo la operación y contiene el elemento inverso de cada elemento en el subconjunto.", "Un subconjunto vacío de un grupo que es cerrado bajo la operación y contiene el elemento inverso de cada elemento en el subconjunto.", "Un subconjunto no vacío de un grupo que es cerrado bajo la operación y contiene el elemento neutro de cada elemento en el subconjunto.", "Un subconjunto no vacío de un grupo que es cerrado bajo la operación y no contiene el elemento neutro.", 1);
preguntas[20]=new pregunta("¿Qué es un grupo abeliano o conmutativo?", "Un grupo en el que la operación es conmutativa, es decir, a * b = b * a para cualquier a y b en el grupo.", "Un grupo en el que la operación no es conmutativa, es decir, a * b != b * a para algunos a y b en el grupo.", "Un grupo en el que todos los elementos tienen el mismo orden.", "Un grupo en el que todos los elementos tienen el mismo elemento inverso.", 1);
preguntas[21]=new pregunta("¿Qué es un homomorfismo en un grupo matemático?", "Una función f que preserva la estructura del grupo, es decir, f(a * b) = f(a) * f(b) para cualquier a y b en el grupo.", "Una función f que transforma cada elemento del grupo en su inverso aditivo.", "Una función f que transforma cada elemento del grupo en su elemento neutro.", "Una función f que transforma cada elemento del grupo en su inverso multiplicativo.", 1);
preguntas[22]=new pregunta("¿Qué es un isomorfismo en un grupo matemático?", "Un homomorfismo biyectivo, es decir, una función f que preserva la estructura del grupo y es uno a uno y sobre.", "Un homomorfismo que no es biyectivo.", "Una función f que transforma cada elemento del grupo en su inverso aditivo.", "Una función f que transforma cada elemento del grupo en su elemento neutro.", 1);
preguntas[23]=new pregunta("¿Qué es un grupo finito?", "Un grupo con un número finito de elementos.", "Un grupo con un número infinito de elementos.", "Un grupo en el que todos los elementos tienen el mismo orden.", "Un grupo en el que todos los elementos tienen el mismo elemento inverso.", 1);
preguntas[24]=new pregunta("¿Qué es un subgrupo generado por un conjunto en un grupo matemático?", "El subgrupo más pequeño que contiene el conjunto dado, es decir, el conjunto de todas las combinaciones lineales con coeficientes enteros de los elementos del conjunto dado.", "El subgrupo más grande que contiene el conjunto dado, es decir, el conjunto de todas las combinaciones lineales con coeficientes enteros de los elementos del conjunto dado.", "El subgrupo generado por los elementos del conjunto dado y su inverso multiplicativo.", "El subgrupo generado por los elementos del conjunto dado y su inverso aditivo.", 0);
preguntas[25]=new pregunta("¿Qué es un subgrupo normal en un grupo matemático?", "Un subgrupo que es cerrado bajo la operación y que satisface la propiedad de que si a es un elemento del subgrupo y g es cualquier elemento del grupo, entonces g * a * g^-1 está en el subgrupo.", "Un subgrupo que no es cerrado bajo la operación y que satisface la propiedad de que si a es un elemento del subgrupo y g es cualquier elemento del grupo, entonces g * a * g^-1 está en el subgrupo.", "Un subgrupo que es cerrado bajo la operación y que satisface la propiedad de que si a es un elemento del subgrupo y g es cualquier elemento del grupo, entonces g * a está en el subgrupo.", "Un subgrupo que es cerrado bajo la operación y que satisface la propiedad de que si a y b son elementos del subgrupo, entonces a * b está en el subgrupo.", 0);
preguntas[26]=new pregunta("¿Qué es un grupo cociente en un grupo matemático?", "Un grupo que se forma al tomar un subgrupo normal de un grupo y considerar los cosets de ese subgrupo.", "Un grupo que se forma al tomar un subgrupo de un grupo y considerar los cosets de ese subgrupo.", "Un grupo que se forma al tomar el conjunto de todos los elementos de un grupo que son iguales a su inverso multiplicativo.", "Un grupo que se forma al tomar el conjunto de todos los elementos de un grupo que son iguales a su inverso aditivo.", 0);
preguntas[27]=new pregunta("¿Qué es una clase lateral en un grupo matemático?", "El conjunto de elementos que se obtienen al multiplicar un elemento del grupo por un elemento dado de un subgrupo.", "El conjunto de elementos que se obtienen al multiplicar un elemento del grupo por un elemento dado que no está en el subgrupo.", "El conjunto de elementos que se obtienen al multiplicar un elemento del subgrupo por un elemento dado del grupo.", "El conjunto de elementos que se obtienen al multiplicar un elemento del subgrupo por un elemento dado que no está en el grupo.", 0);
preguntas[28]=new pregunta("¿Qué es un conjunto generador en un grupo matemático?", "Un conjunto de elementos que puede generar todos los elementos del grupo mediante operaciones de la operación del grupo.", "Un conjunto de elementos que puede generar algunos de los elementos del grupo mediante operaciones de la operación del grupo.", "Un conjunto de elementos que puede generar todos los subgrupos del grupo mediante operaciones de la operación del grupo.", "Un conjunto de elementos que puede generar algunos de los subgrupos del grupo mediante operaciones de la operación del grupo.", 0);
preguntas[29]=new pregunta("¿Qué es un grupo libre en un grupo matemático?", "Un grupo en el que cualquier elemento se puede escribir de forma única como una combinación lineal de los elementos de un conjunto dado, sin restricciones adicionales.", "Un grupo en el que cualquier elemento se puede escribir de forma única como una combinación lineal de los elementos de un conjunto dado, sujeto a restricciones adicionales.", "Un grupo en el que no se pueden escribir todos los elementos de forma única como una combinación lineal de los elementos de un conjunto dado.", "Un grupo en el que cualquier elemento se puede escribir como una combinación lineal",3);
preguntas[30]=new pregunta("¿Qué es un homomorfismo en un grupo matemático?", "Una función entre dos grupos que preserva la estructura de grupo.", "Una función entre dos grupos que cambia la estructura de grupo.", "Una función entre dos grupos que conserva algunos elementos del grupo pero no otros.", "Una función entre dos grupos que intercambia los elementos del grupo.", 0);
preguntas[31]=new pregunta("¿Qué es un isomorfismo en un grupo matemático?", "Un homomorfismo entre dos grupos que es biyectivo.", "Un homomorfismo entre dos grupos que no es biyectivo.", "Una función entre dos grupos que no preserva la estructura de grupo.", "Una función entre dos grupos que intercambia los elementos del grupo.", 0);
preguntas[32]=new pregunta("¿Qué es un endomorfismo en un grupo matemático?", "Un homomorfismo de un grupo en sí mismo.", "Un homomorfismo de un grupo en otro grupo.", "Una función que conserva algunos elementos del grupo pero no otros.", "Una función que intercambia los elementos del grupo.", 0);
preguntas[33]=new pregunta("¿Qué es un automorfismo en un grupo matemático?", "Un isomorfismo de un grupo en sí mismo.", "Un isomorfismo de un grupo en otro grupo.", "Una función que conserva algunos elementos del grupo pero no otros.", "Una función que intercambia los elementos del grupo.", 0);
preguntas[34]=new pregunta("¿Qué es un grupo abeliano?", "Un grupo en el que la operación binaria es conmutativa.", "Un grupo en el que la operación binaria no es conmutativa.", "Un grupo en el que todos los elementos tienen un inverso.", "Un grupo en el que algunos elementos no tienen un inverso.", 0);
preguntas[35]=new pregunta("¿Qué es un semigrupo?", "Un conjunto no vacío con una operación binaria asociativa.", "Un conjunto no vacío con una operación binaria no asociativa.", "Un conjunto vacío con una operación binaria asociativa.", "Un conjunto vacío con una operación binaria no asociativa.", 0);
preguntas[36]=new pregunta("¿Qué es un monoide?", "Un semigrupo con un elemento identidad.", "Un semigrupo sin elemento identidad.", "Un grupo con un elemento identidad.", "Un grupo sin elemento identidad.", 0);
preguntas[37]=new pregunta("¿Qué es un conjunto finito?", "Un conjunto con un número finito de elementos.", "Un conjunto con un número infinito de elementos.", "Un conjunto vacío.", "Un conjunto con un número negativo de elementos.", 0);
preguntas[38]=new pregunta("¿Qué es un conjunto infinito?", "Un conjunto con un número infinito de elementos.", "Un conjunto con un número finito de elementos.", "Un conjunto vacío.", "Un conjunto con un número negativo de elementos.", 0);
preguntas[39]=new pregunta("¿Qué es un conjunto no numerable?", "Un conjunto que no se puede poner en correspondencia uno a uno con los números naturales.", "Un conjunto que se puede poner en correspondencia uno a uno con los números naturales.", "Un conjunto vacío.", "Un conjunto con un número negativo de elementos.", 0);
preguntas[40] = new pregunta("¿Cuál de las siguientes opciones es una propiedad de los grupos abelianos?","Conmutatividad.","Asociatividad.","Existencia de un elemento neutro.","Existencia de inversos.",0);
preguntas[41] = new pregunta("¿Cuál de las siguientes opciones es un ejemplo de monoide?","El conjunto de números naturales con la operación de suma.","El conjunto de números enteros con la operación de multiplicación.","El conjunto de números racionales con la operación de división.","El conjunto de números reales con la operación de resta.",0);
preguntas[42]=new pregunta("¿Qué es un subgrupo de un grupo?", "Un subconjunto no vacío de un grupo que es cerrado bajo la operación del grupo y que contiene el inverso de cada uno de sus elementos.", "Un subconjunto no vacío de un grupo que no es cerrado bajo la operación del grupo y que no contiene el inverso de cada uno de sus elementos.", "Un subconjunto vacío de un grupo.", "Un subconjunto que no es un grupo.", 0);
preguntas[43]=new pregunta("¿Qué es un submonoid de un monoide?", "Un subconjunto no vacío de un monoide que es cerrado bajo la operación del monoide y que contiene el elemento identidad.", "Un subconjunto no vacío de un monoide que no es cerrado bajo la operación del monoide y que no contiene el elemento identidad.", "Un subconjunto vacío de un monoide.", "Un subconjunto que no es un monoide.", 0);
preguntas[44]=new pregunta("¿Qué es un subsemigrupo de un semigrupo?", "Un subconjunto no vacío de un semigrupo que es cerrado bajo la operación del semigrupo.", "Un subconjunto no vacío de un semigrupo que no es cerrado bajo la operación del semigrupo.", "Un subconjunto vacío de un semigrupo.", "Un subconjunto que no es un semigrupo.", 0);
preguntas[45]=new pregunta("¿Cuál es la definición formal de un grupo?","Un conjunto cerrado bajo una operación binaria, con la existencia de un elemento neutro y la existencia de inversos para cada elemento.","Un conjunto cerrado bajo una operación binaria, conmutativa y asociativa.","Un conjunto cerrado bajo una operación binaria, conmutativa y distributiva.","Un conjunto cerrado bajo una operación binaria, asociativa y distributiva.",1);
preguntas[46] = new pregunta("¿Cuál de las siguientes opciones es un ejemplo de monoide?","El conjunto de números naturales con la operación de suma.","El conjunto de números enteros con la operación de multiplicación.","El conjunto de números racionales con la operación de división.","El conjunto de números reales con la operación de resta.",0);
preguntas[47] = new pregunta("¿Cuál de las siguientes opciones NO es un grupo?","El conjunto de números enteros con la operación de multiplicación.","El conjunto de números racionales con la operación de división.","El conjunto de números reales con la operación de suma.","El conjunto de números complejos con la operación de suma.",0);
preguntas[48] = new pregunta("¿Cuál es la definición formal de un monoide?","Un semigrupo con la existencia de un elemento neutro.","Un grupo con la existencia de un elemento neutro.","Un conjunto cerrado bajo una operación binaria y conmutativa.","Un conjunto cerrado bajo una operación binaria y distributiva.",0);
preguntas[49] = new pregunta("¿Cuál de las siguientes opciones es un ejemplo de semigrupo?","El conjunto de números enteros con la operación de multiplicación.","El conjunto de números enteros con la operación de suma.","El conjunto de números racionales con la operación de división.","El conjunto de números naturales con la operación de resta.",0);
